### ISSUE TITLE
Is there a way to know what level of accuracy/format a consumption number is in?

### ISSUE THREAD

**Issue by Shpigford** [allangood/rtlamr2mqtt#183]
I've got an Itron 100G DLN gas meter:

<img width="842" alt="CleanShot 2022-12-13 at 09 43 17@2x" src="https://user-images.githubusercontent.com/35243/207378430-672e3dfb-0036-48da-88bb-9dce5ed40892.png">

And the number reported from `rtlamr2mqtt` is `611959`, which is total consumption.

It's reporting cubic feet, but not sure what what the `format` setting should be for that?

**Comment by airdrummingfool** [comment]
The meter also displays total consumption. You can read the digits from the dials on the meter and compare them to the output of rtlamr2mqtt to see how to adjust the format.

For the first digit, one revolution is 1,000,000. and the digit is on 6 (so 6/10 of one million). So the first digit is 600,000.

The next digit is between 1 and 2, and each revolution is 100,000. So that's 10,000 (always round down).

Keep going until you've read all the digits you can read, and add them up. 600,000 + 10,000 + 1,000 + 700 = 611700.

So your meter dials (at least the ones I can read in the picture) are displaying `611700` cubit feet. That is 6 digits, and the output of rtlamr is also 6 digits; the numbers are also very close together (likely only difference due to a time delay between taking the photo and reading the meter with rtlamr). So your format is `######`.

If, for example, rtlamr read a number 10x that of which was displayed on the meter (e.g. `6119590`), you would use a format that had one decimal spot (`######.#`) to divide that number by 10.
