### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by gshep86** [allangood/rtlamr2mqtt#218]
After about 12 hours, everything stopped coming in. Container still running with no errors, but nothing was being detected. Upon a restart of the container, everything started coming back in. So, can we have the option to restart the container every X mins or hours?

**Comment by onedr0p** [comment]
A health check endpoint that docker can use would be awesome.

https://github.com/allangood/rtlamr2mqtt/issues/224

**Comment by allangood** [comment]
A health check endpoint will not help with this kind of problem. RTLAMR2MQTT is nothing more than a wrapper for 2 other programs: `rtltcp` and `rtlamr`.
This problem happens when `rtltcp` has problems to opens the USB port. The python wrapper never stops to answer or dies and there is no way to know if one of the scripts are having problems of if it is just the utility meter that is not broadcasting.
Keep in mind that not all meters are or behave the same, some will sleep for days or weeks, some broadcast constantly.

Regards.
